### Listar todos los productos

GET http://localhost:1234/products


### Filtras productos por categoría

GET http://localhost:1234/products?category=Monitores

### Obtener un producto por ID

GET http://localhost:1234/products/0f0d518b-b2de-4699-839f-8e2cedab43a0


#### Agregar Producto
POST http://localhost:1234/products
Content-Type: application/json

{
    "name": "Teclado Kumara",
    "price": 39999.00,
    "description": "Potencia pura para tus juegos y desarrollo. Procesador i7, 16GB RAM.",
    "image_url": "https://images.unsplash.com/photo-1603302576837-6378864aacd5?w=500&auto=format&fit=crop&q=60",
    "category_id": "673a6e38-ef5e-11f0-850b-18c04d08d15d"
}

### Actualizar Producto

PATCH http://localhost:1234/products/eea69b22-89ab-4b0f-aa83-fa8e254fc50a
Content-Type: application/json

{
    "name": "Teclado Mecánico Kumara K552",
    "price": 39999.00
}

### Eliminar Producto

DELETE http://localhost:1234/products/c4b69ad8-cbda-4b07-8404-4a61eecb2472


### Registrar Usuario

POST http://localhost:1234/auth/register
Content-Type: application/json

{
    "random": "Campo para verificar que las validaciones funcionen",
    "name": "Santiago",
    "email": "santi3@test.com",
    "password": "123456",
    "phone": 3875708557
}

### Iniciar sesión
POST http://localhost:1234/auth/login
Content-Type: application/json

{
  "email": "santi3@test.com",
  "password": "123456"
}

### Refrescar Token
POST http://localhost:1234/auth/refresh


### Cerrar sesión
POST http://localhost:1234/auth/logout